name: FTP Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**/*'

jobs:
  ftp-ui-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: |
            frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        working-directory: frontend
        run: npm ci -f

      - name: Configure Client
        run: echo "REACT_APP_API_HOST = '${{ secrets.CLIENT_API_HOST }}'" > .env
        working-directory: frontend

      - name: Cache UI build
        uses: actions/cache@v3
        id: cache-build
        with:
          path: client/out
          key: ${{ runner.os }}-build-${{ hashFiles('frontend/**/*.ts', 'frontend/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-build.outputs.cache-hit != 'true' }}
        name: Build UI
        run: |
          export dateNow=$(date +"%d.%m.%Y %H:%M")
          echo "export const update = '$dateNow'" > src/update.ts
          npm run build --if-present
        working-directory: frontend

      - name: Install LFTP client
        run: sudo apt install lftp

      - name: Configure LFTP
        run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

      - name: Load Secrets
        run: echo "machine ${{ secrets.FTP_HOSTNAME }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

      - name: Deploy UI
        run: lftp -e "mirror --parallel=100 -R frontend/build/ /" ${{ secrets.FTP_HOSTNAME }}
